// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzaktzcoxtcumwomqulk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6YWt0emNveHRjdW13b21xdWxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4NTUyNTYsImV4cCI6MjA1NjQzMTI1Nn0.nD2FF2lYvjHF1_KuvcpP9wuDeZ-9WKmBtZk3CKc-b5w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);